### ISSUE TITLE
KAS checkout can't handle fast-forward merges

### ISSUE THREAD

**Issue by lms-jk** [siemens/kas#122]
Our workflow involves fast-forward merges. Switching a meta-layer branch from a merged feature-branch back to the release branch does not work with kas checkout.

As an example, `scarthgap` is the release branch and `devel` is the feature branch of a meta-layer repository `bsp`. During development, the meta-layer was configured to track the feature branch `devel` in the config file:
```yaml
...
repos:
  bsp:
    url: "<our_internal_git_server>"
    branch: devel
    commit: "fab4308300b7b7df5dec4e88bdea2b8c8c91f2cc"
    path: "layers/meta-lms-nvidia-bsp"
...
```
After merging the meta-layer with a fast-forward merge (which does not change the commit hash), the release branch is tracked again:
```yaml
...
repos:
  bsp:
    url: "<our_internal_git_server>"
    branch: scarthgap
    commit: "fab4308300b7b7df5dec4e88bdea2b8c8c91f2cc"
    path: "layers/meta-lms-nvidia-bsp"
...
```
This change will produce the following error message, although "fab4308300b7b7df5dec4e88bdea2b8c8c91f2cc" does exist in branch scarthgap now:
> 2024-04-10 13:56:34 - ERROR - Branch "scarthgap" in repository "bsp" does not contain commit "fab4308300b7b7df5dec4e88bdea2b8c8c91f2cc"

My hypothesis is, that KAS does not fetch the latest revisions from repository `bsp`, because the commit hash already matches. This also means, that KAS misses the update of branch `scarthgap` and complains, that said commit is not contained in the branch.
