### ISSUE TITLE
bblayers order when using path

### ISSUE THREAD

**Issue by kwavnet** [siemens/kas#130]
I have the following two example snippets

base.yml

```yaml
header:
  version: 17
distro: poky
repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    tag: kirkstone-4.0.20
    path: sources/poky
    name: aaaa_poky
    layers:
      meta:
```

and layer1.yml

```yaml
header:
  version: 17
repos:
  somethingelse:
    url: "https://github.com/somethingelse/meta-somethingelse"
    branch: master
    path: sources/meta-somethingelse
    name: zzzz_somethingelse
```

I want to explicitly use name to create some pseudo ordering of the layer (sic 🙄 , I know, but sadly there are vendor layers that need to be included before others).

which ends up with

```
BBLAYERS ?= " \
    ${TOPDIR}/../sources/meta-somethingelse \
    ${TOPDIR}/../sources/poky/meta"
```

in the `bblayers.conf`.
That feels wrong IMO.
I would have expected a alphabetical ordering by `repo-id` and/or `name` from what I read from the current docs.

BTW tests have been done with kas 4.5.

If I now remove the path attribute I end up with

```
BBLAYERS ?= " \
    ${TOPDIR}/../aaaa_poky/meta \
    ${TOPDIR}/../zzzz_somethingelse"
```

which is the order I would have expected, but now the name of the paths make it extra hard to guess what is checked out.

Is that expected behavior?
Did I miss it in the documentation, or might that be something to explicitly state?

https://github.com/siemens/kas/issues/36#issuecomment-784819120 mentions ordering by name, which is not what I see in my example, hence the question
