### ISSUE TITLE
gitconfig zdiff3 breaks kas checkout

### ISSUE THREAD

**Issue by kwalker-plxs** [siemens/kas#153]
I am running kas within a docker image to manage my Yocto project configuration. I recently updated my global gitconfig to set the `merge.conflictstyle` to `zdiff3`. 

While performing a kas checkout of my project, I ran into this error: 
> 2025-05-06 22:15:14 - ERROR    - Command "git checkout -q a82f138b140f613a06bf9ac60101e4bb511c309f -B scarthgap" failed with error 128

If I navigate to the appropriate layer that is being checked out and run the above git checkout, I do not have any issues. 

I found that commenting out the `conflictstyle` or replacing `zdiff3` with `diff3` in my gitconfig makes the issue go away. 

Version Information:
- kas 4.7
- git 2.45.2

Simple inputs for reproduction:
- kas-git-conflictstyle.yml
```
header:
  version: 8

repos:

  meta-freescale:
    url: https://github.com/Freescale/meta-freescale
    branch: scarthgap
    path: layers/meta-freescale
```
- gitconfig
```
[merge]
        conflictstyle = zdiff3
```
