### ISSUE TITLE
quilt patches import for repos

### ISSUE THREAD

**Issue by igaw** [siemens/kas#2]
If you need to patch 3rd repos, e.g. poky, it is cumbersome to clone and provide the sources on your servers/accounts. Instead it would be helpful if kas could apply patches onto of those 3rd party repos.

```yaml
repos:
  meta-foo:
  poky:
     url: "upstream-projects"
     refspec: 388e83aa...33
     patches: 
        add-shallow-tar-file-support : "folder1"
        add-wic-extensions: "folder2"
```

The problem here is, that it is not clear what base path for the folders. 

One way to address the path problem is to use another pair of dictoraries

```yaml
repos:
  meta-foo:
  poky:
     url: "upstream-projects"
     refspec: 388e83aa...33
     patches: 
        add-shallow-tar-file-support:
          repo: meta-foo
          path: "folder1"
        add-wic-extensions: 
          repo: meta-foo
          path: "folder2"
```

Another thing is how to handle after patches have been applied. The refspec changes but the good thing is that with the quilt import we have normal git commits in the tree. So we can figure out if the repos was dirty or not.

Yes, this is what bitbake does and kas starts to be more and more like bitbake. Is it bad, don't know.
