### ISSUE TITLE
cant pul repository from self signed http server

### ISSUE THREAD

**Issue by chezgi** [siemens/kas#55]
when using local git server over self signed https server this error happend:

```
server certificate verification failed. CAfile: none CRLfile: none
```

also using export GIT_SSL_NO_VERIFY=1 not solved the problem.

**Comment by jan-kiszka** [comment]
Could you tell us a bit more details about what you are doing? E.g., are you facing issues with kas itself cloning from that server, or is bitbake stumbling during its fetches?

**Comment by chezgi** [comment]
in this sample:

```
header:
  version: 10
repos:
  meta-test:
      url: https://192.168.1.1/test/meta-test
      layers:
        meta-test-core:
```
we have a  self signed git server at 192.168.1.1

this error happens when  running:
```
kas checkout  myfile.yml
```
