### ISSUE TITLE
Environment variable expansion for `url` and `refspec`

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [siemens/kas#64]
Hey,

Is it possible to use environment variables inside kas config files? That would be very convenient to inject e.g. a deploy token in a CI pipeline. 
For example:
```
repos:
  meta-something:
    url: https://oauth2:${OAUTH_DEPLOY_TOKEN}@git.somecompany.org/reponame
    refspec: ${DEPLOY_REFSPEC}
```
Thanks in advance!
Marius
