### ISSUE TITLE
Add symbolic link feature under repos

### ISSUE THREAD

**Issue by syedelec** [siemens/kas#91]
Hello

I am playing around and I wanted to know if it's possible to integrate the symbolic link feature to reproduce what I was achieving using repo tool

In repo tool, I was doing the following in a manifest ([example](https://github.com/OP-TEE/manifest/blob/master/default.xml#L14)):

```xml
    <project name="meta-custom" remote="remote-name" path="sources/meta-custom" revision="kirkstone">
        <linkfile src="test/script" dest="script"/>  <!--File symlink-->
        <linkfile src="unittests/" dest="unittests"/> <!--Folder symlink-->
    </project>
```

I suggest something like:

```yaml
repos:
  meta-custom:
    url: "http://URLorg/meta-custom"
    refspec: a8c82902384f7430519a31732a4bb631f21693ac
    path: sources/meta-custom
    links:
        [...]
```

Thanks!
