### ISSUE TITLE
feature request : Kas new plugin to set rolling refspec (tag/branches) in yaml manifest to git commits

### ISSUE THREAD

**Issue by embetrix** [siemens/kas#92]
would be nice to have a new plugin to set refspec based on tag/branches to fixed git commits 

$ kas fix-ref kas-project.yml > kas-project-fixed.yml

example of kas-project.yml 
```
header:
  version: 11
machine: qemux86
distro: poky
repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    refspec: kirkstone
    path: "layers"
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded.git"
    refspec: kirkstone
    path: "layers/meta-openembedded"
    layers:
      meta-oe:
      meta-python:
```

will be converted to kas-project-fixed.yml
```
header:
  version: 11
machine: qemux86
distro: poky
repos:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    refspec: 1cb13d24b592986a44fd653e083b7711513fc916
    path: "layers"
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  meta-openembedded:
    url: "https://github.com/openembedded/meta-openembedded.git"
    refspec: bd2d8fba766f912bd1bc5cde7d6f0e72152f1547
    path: "layers/meta-openembedded"
    layers:
      meta-oe:
      meta-python:
```
